### ISSUE TITLE
Error after upgrading to 0.7.0

### ISSUE THREAD

**Issue by aanderse** [aanderse/plugin.program.steam.library#27]
After upgrading to `0.7.0` I get the following error:
```
2020-05-24 10:27:06.257 T:139920669026048   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for int() with base 10: ''
                                            Traceback (most recent call last):
                                              File "/home/aaron/.kodi/addons/plugin.program.steam.library/addon.py", line 2, in <module>
                                                from resources import main
                                              File "/home/aaron/.kodi/addons/plugin.program.steam.library/resources/main.py", line 8, in <module>
                                                import steam
                                              File "/home/aaron/.kodi/addons/plugin.program.steam.library/resources/steam.py", line 19, in <module>
                                                minutesBeforeGamesListsExpiration = int(xbmcplugin.getSetting(int(sys.argv[1]), "games-expire-after-minutes"))  # Default is 3 days
                                            ValueError: invalid literal for int() with base 10: ''
                                            -->End of Python script error report<--
```

@AmineI just wondering if anything jumps out at you.

Contents of `settings.xml`:
```
<settings version="2">
    <setting id="arts-expire-after-months">2</setting>
    <setting id="debug">true</setting>
    <setting id="delete-cache" default="true"></setting>
    <setting id="enable-art-fallback">true</setting>
    <setting id="games-expire-after-minutes">4320</setting>
    <setting id="steam-args" default="true"></setting>
    <setting id="steam-exe">/run/current-system/sw/bin/steam</setting>
    <setting id="steam-id">-</setting>
    <setting id="steam-key">-</setting>
    <setting id="steam-path">/home/aaron/.steam</setting>
    <setting id="version">0.6.0</setting>
</settings>
```

**Comment by AmineI** [comment]
Shoot, I can't seem to reproduce this issue.. There are two int() calls, one for the setting and one for the handle, and I can't see anything wrong with them right now 🤔.. I'll try to troubleshoot that. 

For your environment, can I assume it's on Kodi 18.7, when upgrading from 0.6.3 to 0.7.0 ?

**Comment by AmineI** [comment]
In steam.py I used [xbmcplugin.getSetting(handle,id)](https://codedocs.xyz/AlwinEsch/kodi/group__python__xbmcplugin.html#ga8739303a25018f275578b17e35602793) and not [__addon__.getSetting(id)](https://codedocs.xyz/AlwinEsch/kodi/group__python__xbmcaddon.html#ga5d250618833bd3c2b2954db4f36b1655) as we did everywhere else. 

Setting aside the consistency issue (apologies for that one !), I'm still not sure why it didn't work on both our configs. Should be fixed by the PR.

**Comment by aanderse** [comment]
@AmineI I'm not running the latest `kodi`:
```
~> kodi --version                                                                                                                                                                                   
18.5 Git:20191116 Media Center Kodi
Copyright (C) 2005-2019 Team Kodi - http://kodi.tv
```

I'll try the PR out today. Thanks!
